baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ola-iya'
theme = 'gokarna'
showpostsonhomepage = "recent"
numberpostsonhomepage = 4
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/writeups/"
    weight = 1
